/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 public/models/cyberpunk_bike/cyberpunk_bike.glb
Author: daCruz (https://sketchfab.com/daCruz)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/cyberpunk-bike-efcf679a115c487face1adc2ce7e8b8c
Title: Cyberpunk bike
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cyberpunk_bike.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[615.104, -51.26, 52.76]} rotation={[0, 0, -3.137]} scale={0.012}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.lambert3SG} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.initialShadingGroup} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.initialShadingGroup} />
      </group>
    </group>
  )
}

useGLTF.preload('/cyberpunk_bike.glb')
