/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 ./public/texting.glb
*/

import React, { useRef, useEffect} from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { LoopOnce } from 'three'
import * as THREE from 'three'


export default function Model() {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/texting.glb')
  const { actions } = useAnimations(animations, group)
  const vec = new THREE.Vector3()

  useEffect(()=>{
    console.log('second actions',actions)
    console.log('nodes',nodes)

    actions['Armature|mixamo.com|Layer0'].setLoop(LoopOnce).play().halt(5)
    
  })
  return (
    <group ref={group} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Alpha_Joints" geometry={nodes.Alpha_Joints.geometry} material={materials.Alpha_Joints_MAT} skeleton={nodes.Alpha_Joints.skeleton} />
          <skinnedMesh name="Alpha_Surface" geometry={nodes.Alpha_Surface.geometry} material={materials.Alpha_Body_MAT} skeleton={nodes.Alpha_Surface.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/texting.glb')
